### ISSUE TITLE
[request] "Total resources needed"-line

### ISSUE THREAD

**Issue by Dan-Gecko** [crissian/x4#11]
First and foremost: Thank you! This tool is simple and great for planing stations with a certain output-ratio!

It would be great (and probably easy), if you could add 3 more rows somewhere in the "Station Summary" column stating the total amount of resources needed (not total cost but amount). Something simple like this:

total Claytronics x X
total Energy Cells x Y
total Hull Parts x Z

where X, Y, Z are the sum of each resource respectively.

Cheers!

**Comment by crissian** [comment]
Not sure I understand. Isn't that already displayed if you expand the Expenses under Production Per Hour?

**Comment by Rayman2200** [comment]
Hi, he mean the building costs in resources. So it will be easier to ship the required resources from the own stations. 

![image](https://user-images.githubusercontent.com/1431436/54744059-3ff2df00-4bc6-11e9-9a11-beabce9d82c5.png)

**Comment by Dan-Gecko** [comment]
The example, Rayman2200 provided shows exactly what I meant. Thanks for the nice screenshot!

**Comment by crissian** [comment]
Implemented by @Rayman2200, thanks.
