### ISSUE TITLE
"Share" button generates text which can't be imported anywhere.

### ISSUE THREAD

**Issue by iamflash** [crissian/x4#110]
What sense in existing "Share" opportunity when there is no way to import outcome text?

**Comment by crissian** [comment]
I don't understand the issue.

**Comment by iamflash** [comment]
Introduction:
There is "Share" button at "Station calculator" page. It generates csv text.
Issue:
There is no way to import that csv text to recreate station. "Import" button works only with xml files.

**Comment by crissian** [comment]
Was it a bot post?
There's not CSV text, the share button is used for you to share a layout link on the web, forum etc.

**Comment by iamflash** [comment]
> Was it a bot post? There's not CSV text, the share button is used for you to share a layout link on the web, forum etc.

that shared layout has to be somehow observed. Can you explain what button should be pressed (or other steps to perform) to recreate layout within station calculator page for those who only have that generated text?

**Comment by crissian** [comment]
Just open a new browser window and paste the link, click enter. Basic internet skills.

**Comment by iamflash** [comment]
> Just open a new browser window and paste the link, click enter. Basic internet skills.

its just url link. My bad. xD Thought its somewhat specific text like xml. Thanks
