### ISSUE TITLE
www.x4-game.com only shows a 404 error

### ISSUE THREAD

**Issue by ThomasAH** [crissian/x4#12]
Hi!

When opening http://www.x4-game.com/ in a web browser, I get a 404 error with
"Oops, looks like the page is lost. This is not a fault, just an accident that was not intentional."
It worked some days ago.

DNS information (in case the server has moved and I'm seeing the wrong host):
```
www.x4-game.com is an alias for x4-game.com.
x4-game.com has address 185.224.138.162
```

(Thank you for providing this very helpful service _and_ the sources!)

**Comment by crissian** [comment]
My hosting expired. It's fixed now, so refresh the page.

**Comment by ThomasAH** [comment]
Thank you, it works again!
