### ISSUE TITLE
Update data files for X4 2.6

### ISSUE THREAD

**Issue by bitvoid** [crissian/x4#15]
First of all a big thank you for creating this awesome tool!

X4 2.6 contained a couple of economy balancing changes so I think the data files need to be updated. From the changelog:

```
Improved balancing and robustness of in-game economy (including prices, volume and production rates of Engine Parts, Hull Parts and Smart Chips).
```

Would you also consider releasing the tool you used for converting the game data files?

Thank you for your hard work.

**Comment by crissian** [comment]
Hey, I just updated the data files from the game files.

> Would you also consider releasing the tool you used for converting the game data files?

That's a quick and dirty tool with a nasty code that I wouldn't want to see associated with my name :-)

**Comment by bitvoid** [comment]
Thank you for the update.

> That's a quick and dirty tool with a nasty code that I wouldn't want to see associated with my name :-)

As a developer who built similar "one-off" tools in the past I can relate to that :)
