### ISSUE TITLE
 How to extract the data from the game files？

### ISSUE THREAD

**Issue by LokiSharp** [crissian/x4#3]

**Comment by LokiSharp** [comment]
Is those all in the libraries\wares.xml?

**Comment by crissian** [comment]
There are multiple files, wares.xml is the starting point.

**Comment by LokiSharp** [comment]
Thank for your reply.
I am going to modify your project to support i18n. At first, I'm trying to create a converter to convert the xml without localization strings. And separate the data from the code.
I see you already convert the xml format to json format. Has there a converter by official or you create by youself? If you create a tool, can you share it?

**Comment by crissian** [comment]
I did create a tool, however it's something quick that I made quick and dirty, nothing really I'd want to share. It's a C# tool that I can give you access you if really want, however don't expect anything fancy.

**Comment by LokiSharp** [comment]
I read you converter. It's nice, I only need to modify little code.
In order to change the code structure as little as possible. 
For data file, I think I only need to modify the translation xml path, then use the .ts output file. 
For app, I‘m trying to add i18n with Angular's i18n feature.

At last, Can I post a X4 calculator with Chinese at china network?

**Comment by LokiSharp** [comment]
@crissian Can you give me the new X4Extractor? I'm try to upgrade data to ver 4.0
