### ISSUE TITLE
Advanced Electronics production values incorrect

### ISSUE THREAD

**Issue by AndLindemann** [crissian/x4#30]
I think Advanced Electronics production values are incorrect. It shows that a cycle should use 120 Quantum Tubes, however in-game it uses 200 Quantum Tubes.
A bit unsure as I tried to look into your data files and everything seems to be divided by 6 somehow, so not sure how it's calculated. Maybe you can check?

**Comment by AqlaSolutions** [comment]
Yup, I'm also confused. According to the calculator it consumes 300/h energy cells and produces 300/h electronics, but in the game encyclopedia it shows 180 consumption and 72 production which should be per cycle of ?? minutes. In station logistics it shows 900/h consumption and 360/h production (when that checkbox above checked). Values in calculator are simple wrong. May be economic mods play some role here.

**Comment by crissian** [comment]
```
<ware id="advancedelectronics" name="{20201,101}" description="{20201,102}" factoryname="{20201,104}" group="shiptech" transport="container" volume="30" tags="container economy stationbuilding">
    <price min="710" average="1014" max="1318" />
    <production time="720" amount="60" method="default" name="{20206,101}">
      <primary>
        <ware ware="energycells" amount="60" />
        <ware ware="microchips" amount="44" />
        <ware ware="quantumtubes" amount="20" />
      </primary>
      <effects>
        <effect type="work" product="0.22" />
      </effects>
    </production>
    <icon active="ware_advancedelectronics" video="ware_advancedelectronics_macro" />
  </ware>
```

This is in game files.
Meaning the cycle is 720 seconds = 12 minutes, so 5 cycles per hour
Each cycle consumes 60 energy cells, 44 microchips and 20 quantum tubes.

With max workers, the efficiency can reach a max of 122%

This xml is extracted from game files and transformed into this:
https://github.com/crissian/x4/blob/dev/src/app/shared/services/data/wares-data.ts

**Comment by crissian** [comment]
According to their online wiki, my numbers match:

https://www.egosoft.com:8444/confluence/display/X4WIKI/Production+Modules

**Comment by crissian** [comment]
Please note I **DO NOT** support any mods and I don't plan to.

**Comment by AqlaSolutions** [comment]
Ok, what do I need to build modified version of calculator? I mean which compilers/tooling?

**Comment by crissian** [comment]
The code is angular / typescript.
Visual Studio Code, Atom IO, WebStorm etc

**Comment by AqlaSolutions** [comment]
Just in case someone else needs it here is a patched version of calculator to be used with Faction Enhancer - Econ Balance Module. To use:
 `cmd => cd [calculator_directory] => python  -m SimpleHTTPServer`

[X4 calculator2.zip](https://github.com/crissian/x4/files/4650533/X4.calculator2.zip)
