### ISSUE TITLE
Autofill add more than necessary and forgot workforce

### ISSUE THREAD

**Issue by EikiProg** [crissian/x4#36]
I test the auto fill in 2 configuration and both result in the same problem:

**1st complex:** (All resources a green appart from ice)
- 1x Argon L Habitat
- 1x Argon S Habitat
- 3x Food Ration Production
- 6x Argon Medical Supply Production
- 1x Wheat Production
- 1x Spice Production
- 1x Meat Production
- 1x Water Production
- 1x Energy Cell Production

**2nd complex:**
- 1x Argon L Habitat
- 1x Argon S Habitat
- 3x Food Ration Production
- 6x Argon Medical Supply Production

**The result I get is :**
- 1x Argon L Habitat
- 1x Argon S Habitat
- 3x Food Ration Production
- 6x Argon Medical Supply Production
- **2x Wheat Production**
- **2x Spice Production**
- **2x Meat Production**
- **2x Water Production**
- 1x Energy Cell Production

It seem to not take into account the workforce actualy in the complex because.
If I put the workforce to 0, in the station resources collumn I can see that Meat, Spices and Wheat are in the red.

And the other issue is that it did not add Habitation module.
I think that on clicking the autofill button they should be some check like follow:
- If there is Habitation module already in the complex go on
- If there is some race specific module, extract the race of it to add Habitation module
- If not promp to get the race you want for the Habitation module

**Comment by Rayman2200** [comment]
This is already addressed in https://github.com/crissian/x4/pull/32

**Comment by EikiProg** [comment]
Ok sorry, only checked the open issue, will close this one.
