### ISSUE TITLE
Tweaking the list parameters don't stays saved when navigation back

### ISSUE THREAD

**Issue by MindTooth** [crissian/x4#38]
Hi,

Love the site very much..  Thank you! 👍🏻

One thing that I find a bit annoying is that when I click a ship after I've sorted by name and increased the list size to 40, navigating back resets my choices.  Is that something that could easily be fixed?

I'm not that into JS as of yet, and I'm not sure that I can be of help.  Maybe I'll take a grab at it, but not for long.

**Comment by Rayman2200** [comment]
There is programmatically a option to enable the storing of filters and sorting of the table. 

`
<dxo-state-storing [enabled]="true" type="localStorage" storageKey="shipFilter"></dxo-state-storing>
`

Should be added to the `<dx-data-grid>` element of the table. 

I have a pending PullRequest with this feature which is still "Work In Progress"

You could check out temporary the developed state under https://x4-game.netlify.app/ but there is no guarantee that the branch will be held up to date.

**Comment by MindTooth** [comment]
Preliminary testing show that it works great!  Thanks. 🙏
