### ISSUE TITLE
Is this data hand crafted or is there a utility written to construct it from game data?

### ISSUE THREAD

**Issue by jakotheshadows** [crissian/x4#47]
At least some of the modules in `x4/src/app/shared/services/data/wares-data.ts` are out of date after one or more patches that came out this year. Was this file manually made or is there an existing utility that is used to regenerate it after each patch? If a utility exists, where might it be found so that this service data can be updated?

**Comment by crissian** [comment]
There is obviously a utility that extracts the data from the game files, I'm not manually doing that work. The utility is not made available mostly because it's just code thrown to get the shit done, but I don't want to associate the quality of that code with my name :-)

**Comment by jakotheshadows** [comment]
Haha! Fair enough. I've slogged through these XML files and can imagine the horrors you were forced to endure in writing that utility. I don't suppose I could bribe you into running that utility and pushing the changes by buying you a coffee? 😄

**Comment by crissian** [comment]
I just updated the data. Should be up and running.

**Comment by jakotheshadows** [comment]
![image](https://user-images.githubusercontent.com/5022541/103355361-09751400-4a7c-11eb-924e-5c0c5f82e127.png)
I'm guessing its still deploying or something, but after a hard refresh I'm still getting 6600 for water at 100% efficiency (should be 5790, unless my math is off)

**Comment by crissian** [comment]
Water: amount 220 units produced in 120 seconds at 100% efficiency. Is this correct?

**Comment by crissian** [comment]
from `wares.xml`

```xml
<ware id="water" name="{20201,4701}" description="{20201,4702}" factoryname="{20201,4704}" group="water" transport="container" volume="6" tags="container economy">
    <price min="32" average="53" max="74" />
    <production time="120" amount="220" method="default" name="{20206,101}">
      <primary>
        <ware ware="energycells" amount="60" />
        <ware ware="ice" amount="320" />
      </primary>
      <effects>
        <effect type="work" product="0.25" />
      </effects>
    </production>
    <container ref="sm_gen_pickup_liquid_01_macro" />
    <icon active="ware_water" video="ware_water_macro" />
  </ware>
```

**Comment by jakotheshadows** [comment]
Oops! I was running the beta - that explains why some numbers seemed off! Just bought you some coffees sorry to waste your time lol.
