### ISSUE TITLE
[Request] Solar Power Efficiency

### ISSUE THREAD

**Issue by Hurric4ne** [crissian/x4#54]
First off, thanks for updating the station module information to 4.0 so fast.
Since the game now has different sunlight values depending on the Sector's distance to the Sun, this should maybe be added to the Station Module as a seperate Input field/slider (or a seperate dropdown to set the sector itself, but that would mean more maintenance if they change the values)

**Comment by crissian** [comment]
I didn't know they added sunlight to the game. I noticed only terran regions have values different than 100%. I'll investigate it and see how I can add this to the station planner.

**Comment by andrewd18** [comment]
The new 5.0 Tides of Avarice system "Avarice" provides 1390% sunlight. Bright Promise (Teladi) provides 200% sunlight. As mentioned the Terran systems also provide bonus/malus sunlight at varying levels.
