### ISSUE TITLE
Workers consumption

### ISSUE THREAD

**Issue by SimoneEnet** [crissian/x4#55]
Hello,
the amount of resources used by the station workers doesn't seem to match what there is in-game.

For example, the MRE consumption for 10 L Terran habitats should be `255*5000/400=3187.5`, and that's, in fact, the result on the calculator: http://www.x4-game.com/#/station-calculator?l=@$module-module_ter_hab_l_01,count:10
But in-game (v4.00 432831, no mods) I'm getting a wildly different result:
![20210318220853_1](https://user-images.githubusercontent.com/19184052/111702373-75297a80-883c-11eb-9695-fd29497c2069.jpg)

I searched the Egosoft forums but all I was able to find were threads about "station food shortages", which kind of confirms that there have been changes, but doesn't really help in finding what changed.

Since the data is imported directly from the game files I'm assuming it to be correct, and that the error has to be in the formula.

Any idea on how to get the new formula? If I were to ask on the Egosoft forums, should I try asking on the main forum, or on the Scripts and Modding one?

Thanks

**Comment by crissian** [comment]
They changed 400 to 200 per hour, which means now it needs double the resources.

**Comment by crissian** [comment]
Good catch, I've added the fix. Also note that if you have more workers than needed, they consume less.

```xml
<add sel="/wares/ware[@id='workunit_busy']">
<production time="3600" amount="200" method="terran" name="{20206,901}">
<primary>
<ware ware="medicalsupplies" amount="270"/>
<ware ware="terranmre" amount="255"/>
</primary>
</production>
</add>
<add sel="/wares/ware[@id='workunit_idle']">
<production time="3600" amount="200" method="terran" name="{20206,901}">
<primary>
<ware ware="medicalsupplies" amount="180"/>
<ware ware="terranmre" amount="170"/>
</primary>
</production>
</add>
```
