### ISSUE TITLE
Station database

### ISSUE THREAD

**Issue by xtc0r** [crissian/x4#8]
Would you consider to add a station database to you website? Would be great if the community could upload their station layouts + a picture. The website could scan the layout file to list the modules, needed resources, produced resources, possible profit, manpower etc.

Not sure if you are aware of the Egosoft / X4 discord channel. Maybe you want join it if not done yet. A lot of modders hanging out there.

https://discord.gg/J8u6Kdc

**Comment by crissian** [comment]
Thanks for the suggestions. The app currently does not store anything on the server and it doesn't even have any server side code. Everything is client side.

Your request requires server side coding and while I would be willing to do it, I don't think I am willing to cover the hosting costs from my own pocket :-)

However I just join the discord server and I am willing to think about adding server side functionality to it.

My username is crissian.

**Comment by xtc0r** [comment]
Thanks for thinking about it. Maybe there is a better solution instead of doing it on the server. The users could do it and provide a data format which you only display on your website. Very similar to the stations calculator. 
Asking in the #x4 modding forum about a best practice could bring up some more and better ideas than I might come up with :)

**Comment by crissian** [comment]
Isn't this scenario covered by share plan functionality? For example:
[http://www.x4-game.com/#/station-calculator?l=@$module-module_par_prod_sojabeans_01,count:6;,$module-module_gen_prod_energycells_01,count:1;,$module-module_gen_prod_water_01,count:1;,$module-module_arg_hab_l_01,count:1](http://www.x4-game.com/#/station-calculator?l=@$module-module_par_prod_sojabeans_01,count:6;,$module-module_gen_prod_energycells_01,count:1;,$module-module_gen_prod_water_01,count:1;,$module-module_arg_hab_l_01,count:1)

**Comment by xtc0r** [comment]
I think that's different. With share plan you only tell the user which modules are needed to produce X goods with Y amount and Z needed resources. But you still have to put it together yourself in the game.

This means:

- more effort
- no fancy design, because other might spent hours to create some awesome stations.

Where a database of really in game stations would serve as a pool of really great stations where you can pick one which fulfills your needs and style of looking.

**Comment by hreikin** [comment]
> Your request requires server side coding and while I would be willing to do it, I don't think I am willing to **cover the hosting costs** from my own pocket :-)

I am a web designer and would be able to provide some "Shared Hosting" for the project for free if it would help ?

**Comment by setreadygo** [comment]
I personally don't need/want this feature I just want to chime in to save you some money in the event you go ahead with it, this can be done locally using the http5 file reader api

http://caniuse.com/#feat=filereader
http://www.html5rocks.com/en/tutorials/file/dndfiles/

Save files are gzipped + xml so you'd need decoders for those
https://www.npmjs.com/package/pako
https://github.com/pladaria/xml-reader

**Comment by xirsoi** [comment]
Save files are also millions of lines long and hundreds of megabytes when uncompressed. See the related ticket for uploading saves to the server for the discussion there.

**Comment by crissian** [comment]
I do not plan to support this feature, this would greatly affect my hostings costs the the current app doesn't have any source of monetization. Closing the issue.
