### ISSUE TITLE
Making "Resources are provided by other stations" and "Miners provide basic resources" ware specific

### ISSUE THREAD

**Issue by Exidrial** [crissian/x4#9]
I would like to be able to tick the "Resources are provided by other stations" and "Miners provide basic resources" checkboxes for each ware individually in order for me to better estimate the profits my station is going to make.

1: In the summary component (?) "Expenses" there is a new checkbox called something like "Wares provided by other sources" next to each ware that nulls this  specific wares cost.

2: The current "Resources are provided by other stations" and "Miners provide basic resources" checkboxes are removed.

Offtopic: I'd love to do this myself but I'm struggling with setting up my IDE right now.  I'm just an apprentice with mostly Java and minor HTML/PHP/CSS experience but I'd love to contribute to this project in the future.

**Comment by crissian** [comment]
I like the idea and I'll do it in the next few days.
