### ISSUE TITLE
X4 Kingdom End

### ISSUE THREAD

**Issue by elidiak** [crissian/x4#91]
Add to planner all Boron station parts and commodities

**Comment by Pasukaru** [comment]
Is there some tool to extract the data from game files (and possibly map it to the json structure that's used by this calculator)?

I tried doing it by hand, but looking through roguey and the in-game encyclopedia, they are both not accurate enough to easily map it to what this calculator needs, so I quickly gave up on the manual approach.

**Comment by VladisM** [comment]
Hi, I found out this tool https://github.com/bno1/X4FProjector, maybe that can be used? I don't know, I'm still new to this game. 

Anyway, is original author still interested in this project? I would also appreciate update with new stuffs. (unfortunately I cannot help too much, as I don't understand TypeScript at all)

**Comment by crissian** [comment]
I have my own extraction tool, I'm working on an update for the app. Coming soon ...

**Comment by VladisM** [comment]
Thank you @crissian! :) Sorry for my doubt about you. :D

**Comment by elidiak** [comment]
Boron L Oasis still using Argon food rations

**Comment by crissian** [comment]
> Boron L Oasis still using Argon food rations

You're right, I just fixed it.

**Comment by elidiak** [comment]
Thanks for your work. Boron L Oasis 450 BoFu 990 Medical Supplies 810 water Boron M Oasis 225 BoFu 445 Medical Supplies 405 Water Boron S Oasis 113 BoFu 248 Medical Supplies 203 Water
