### ISSUE TITLE
Feature Suggestion: Systems / Sunlight Modifier

### ISSUE THREAD

**Issue by Effect0ne** [crissian/x4#92]
Systems can affect certain production processes.  Most notably, sunlight affects how efficient solar cell production is.  Additionally, systems contain only certain resources.  The following would be useful:

1. Solar cell production: Either: 1) the ability to select the system sunlight % for solar cell production on the right hand side somewhere; or 2) the ability to select the system the station will be built in for this information to be populated automatically.

2. If system selection is made available, the web app telling you what resources are available in system and what aren't (assuming each game has the same system resource distribution, which I think it does but apologies if I am incorrect here).

**Comment by elidiak** [comment]
Please consider that this is developed by one community member in his spare time. Rather than a system select, a single field for an efficiency multiplier would do the same thing and take less time.

**Comment by Effect0ne** [comment]
Absolutely.  That's why for number 1 I gave an either/or :)

I'll edit the title to make it clearer.

**Comment by crissian** [comment]
I've added the Sunlight Modifier. If anybody can help me identify where in the game xml structure is the information about map structure (system / region etc) I could add the sunlight region info to the calculator.
