### ISSUE TITLE
Unable to complete import

### ISSUE THREAD

**Issue by theneofusion** [crissian/x4#93]
Hello,
Description of the issue:
Since the KE update I am unable to import my constructionplans.xml.
Pre-KE this worked fine.

OS: macOS Monterey
Tested Webbrowsers: Safari 16.4.1 and Chrome 112.X

Steps to reproduce:
1. I have reloaded the page.
2. I click the Import-button in the top menu which opens up the "Import Plans"-dialogue window.
3. I copy and paste the contents of my constructionplans.xml into the designated field (sample file attached to the issue but with file ending swapped to txt since github does not allow xml uploads).
4. I click the "Import"-button at which point nothing more happens. The window does not close and no import initates. The Import-button responds to mouseover hover, but the event that should fire on click appears to fail or not trigger at all.
5. The window can be closed with the Cancel-button.

[constructionplans.txt](https://github.com/crissian/x4/files/11296747/constructionplans.txt)

**Comment by crissian** [comment]
Thanks, I just fixed it, please try it.
